name: Create Interrogation PR

on:
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Create questions file
        run: |
          mkdir -p interrogation
          echo "## Shailyay Interrogation" > interrogation/questions-${{ env.date }}.md
          echo "" >> interrogation/questions-${{ env.date }}.md
          echo "1. What do you think I like about you?" >> interrogation/questions-${{ env.date }}.md
          echo "2. What do you like about me?" >> interrogation/questions-${{ env.date }}.md
          echo "3. Hypothetically, if your boyfriend asked you to a dance, what would you HAVE to do at the dance?" >> interrogation/questions-${{ env.date }}.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Create interrogation file with questions"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          base: main
          branch: interrogation-${{ env.date }}
          title: "Shailyay Interrogation - ${{ env.date }}"
          body: |
            Here are your questions to answer:
            - [ ] What do you think I like about you?
            - [ ] What do you like about me?
            - [ ] Hypothetically, if your boyfriend asked you to a dance, what would you HAVE to do at the dance?

            Go to **Files changed** and answer these questions! 💌
          labels: 💌, question
