name: E-Ball Invite
on:
  workflow_dispatch

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Create E-Ball invite file
        run: |
          mkdir -p invitations
          echo "## My E-Ball Reflection" > invitations/eball-question-${{ env.date }}.md
          echo "I'm hoping this gets merged 💙" >> invitations/eball-question-${{ env.date }}.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "E-Ball big question invite"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: main
          branch: eball-invite-${{ env.date }}
          title: "E-Ball big question"
          body: |
            Would you be my date to E-Ball?

            - [ ] YES!!
            - [ ] ABSOLUTELY
            - [ ] DEFITNETLTY!!!
